/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        
        FeedbackPanel.setLayout(new BoxLayout(FeedbackPanel, BoxLayout.Y_AXIS));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        feedback_btn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        bookingsbtn = new javax.swing.JButton();
        discoverbtn = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        myeventsbtn = new javax.swing.JButton();
        plus_btn = new javax.swing.JButton();
        taskbar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FeedbackScroll = new javax.swing.JScrollPane();
        FeedbackPanel = new javax.swing.JPanel();
        event_btn = new javax.swing.JButton();
        user_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(208, 202, 232));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedback_btn.setBackground(new java.awt.Color(208, 202, 232));
        feedback_btn.setText("Feedback");
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });
        sidebar.add(feedback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, 50));

        homebtn.setBackground(new java.awt.Color(208, 202, 232));
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        sidebar.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 50));

        bookingsbtn.setBackground(new java.awt.Color(208, 202, 232));
        bookingsbtn.setText("Bookings");
        sidebar.add(bookingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 50));

        discoverbtn.setBackground(new java.awt.Color(208, 202, 232));
        discoverbtn.setText("Discover");
        discoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverbtnActionPerformed(evt);
            }
        });
        sidebar.add(discoverbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 50));

        profilebtn.setBackground(new java.awt.Color(208, 202, 232));
        profilebtn.setText("Profile");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        sidebar.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 50));

        logout_btn.setBackground(new java.awt.Color(208, 202, 232));
        logout_btn.setText("Log Out");
        sidebar.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 220, 40));

        myeventsbtn.setBackground(new java.awt.Color(208, 202, 232));
        myeventsbtn.setText("My Events");
        myeventsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myeventsbtnActionPerformed(evt);
            }
        });
        sidebar.add(myeventsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 50));

        plus_btn.setBackground(new java.awt.Color(208, 202, 232));
        plus_btn.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        plus_btn.setText("+");
        plus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_btnActionPerformed(evt);
            }
        });
        sidebar.add(plus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 60, 50));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 256, 630));

        taskbar.setBackground(new java.awt.Color(229, 179, 208));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Home");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/326656_home_icon.png"))); // NOI18N

        javax.swing.GroupLayout taskbarLayout = new javax.swing.GroupLayout(taskbar);
        taskbar.setLayout(taskbarLayout);
        taskbarLayout.setHorizontalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        taskbarLayout.setVerticalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 710, 40));

        FeedbackScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        FeedbackScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        FeedbackPanel.setLayout(new javax.swing.BoxLayout(FeedbackPanel, javax.swing.BoxLayout.LINE_AXIS));
        FeedbackScroll.setViewportView(FeedbackPanel);

        getContentPane().add(FeedbackScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 330, 490));

        event_btn.setText("jButton1");
        getContentPane().add(event_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 100, 40));

        user_btn.setText("jButton1");
        getContentPane().add(user_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_feedback_btnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_feedback_btnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_homebtnActionPerformed

    private void discoverbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_discoverbtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_discoverbtnActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_profilebtnActionPerformed

    private void myeventsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_myeventsbtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_myeventsbtnActionPerformed

    private void plus_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plus_btnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_plus_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JScrollPane FeedbackScroll;
    private javax.swing.JButton bookingsbtn;
    private javax.swing.JButton discoverbtn;
    private javax.swing.JButton event_btn;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton myeventsbtn;
    private javax.swing.JButton plus_btn;
    private javax.swing.JButton profilebtn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel taskbar;
    private javax.swing.JButton user_btn;
    // End of variables declaration//GEN-END:variables

    public void updateDashboardCounts(int userCount, int eventCount) {
        user_btn.setText("Users: " + userCount);
        event_btn.setText("Events: " + eventCount);
    }

    public JPanel getFeedbackPanel() {
        return FeedbackPanel;
    }

    //btns
    public void addLogoutListener(ActionListener listener) {
        logout_btn.addActionListener(listener);
    }

    public void addUserListener(ActionListener listener) {
        user_btn.addActionListener(listener);
    }

    public void addProfileListener(ActionListener listener) {
        profilebtn.addActionListener(listener);
    }

    public void addCreateEventListener(ActionListener listener) {
        plus_btn.addActionListener(listener);
    }

    public void addEventListener(ActionListener listener) {
        event_btn.addActionListener(listener);
    }

    public void addBookingListener(ActionListener listener) {
        bookingsbtn.addActionListener(listener);
    }

    public void addHomeListener(ActionListener listener) {
        homebtn.addActionListener(listener);
    }

    public void addDiscoverListener(ActionListener listener) {
        discoverbtn.addActionListener(listener);
    }

    public void addMyEventsListener(ActionListener listener) {
        myeventsbtn.addActionListener(listener);
    }

    
}
