/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author hp
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public AdminProfile() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        feedback_btn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        bookingsbtn = new javax.swing.JButton();
        myeventsbtn = new javax.swing.JButton();
        discoverbtn = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        taskbar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pic_lbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        upload_btn = new javax.swing.JButton();
        email_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        phone_lbl = new javax.swing.JLabel();
        regdate_lbl = new javax.swing.JLabel();
        accstatus_lbl = new javax.swing.JLabel();
        name_fld = new javax.swing.JTextField();
        email_fld = new javax.swing.JTextField();
        phone_fld = new javax.swing.JTextField();
        regdate_fld = new javax.swing.JTextField();
        accstatus_fld = new javax.swing.JTextField();
        cam_lbl = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        deactivate_btn = new javax.swing.JButton();
        viewact_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(208, 202, 232));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedback_btn.setBackground(new java.awt.Color(208, 202, 232));
        feedback_btn.setText("Feedback");
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });
        sidebar.add(feedback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, 50));

        homebtn.setBackground(new java.awt.Color(208, 202, 232));
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        sidebar.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 50));

        bookingsbtn.setBackground(new java.awt.Color(208, 202, 232));
        bookingsbtn.setText("Bookings");
        sidebar.add(bookingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 50));

        myeventsbtn.setBackground(new java.awt.Color(208, 202, 232));
        myeventsbtn.setText("My Events");
        sidebar.add(myeventsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 50));

        discoverbtn.setBackground(new java.awt.Color(208, 202, 232));
        discoverbtn.setText("Discover");
        discoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverbtnActionPerformed(evt);
            }
        });
        sidebar.add(discoverbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 50));

        profilebtn.setBackground(new java.awt.Color(180, 175, 204));
        profilebtn.setText("Profile");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        sidebar.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 50));

        jButton1.setBackground(new java.awt.Color(208, 202, 232));
        jButton1.setText("Log Out");
        sidebar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 220, 40));

        bg.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 256, 630));

        taskbar.setBackground(new java.awt.Color(229, 179, 208));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Profile");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N

        javax.swing.GroupLayout taskbarLayout = new javax.swing.GroupLayout(taskbar);
        taskbar.setLayout(taskbarLayout);
        taskbarLayout.setHorizontalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        taskbarLayout.setVerticalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 700, 40));

        pic_lbl.setBackground(new java.awt.Color(102, 204, 255));
        pic_lbl.setForeground(new java.awt.Color(153, 255, 0));
        pic_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pic_lbl.setPreferredSize(new java.awt.Dimension(134, 172));
        bg.add(pic_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 130, 140));
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        upload_btn.setText("Upload your Profile Picture");
        upload_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btnActionPerformed(evt);
            }
        });
        bg.add(upload_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        email_lbl.setText("Email");
        bg.add(email_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        name_lbl.setText("Full Name");
        bg.add(name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        phone_lbl.setText("Contact Number");
        bg.add(phone_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        regdate_lbl.setText("Registration Date");
        bg.add(regdate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        accstatus_lbl.setText("Account Status");
        bg.add(accstatus_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        name_fld.setText("Enter your name");
        name_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fldActionPerformed(evt);
            }
        });
        bg.add(name_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 220, -1));

        email_fld.setText("Enter your email");
        bg.add(email_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 220, -1));

        phone_fld.setText("Enter your phone number");
        bg.add(phone_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 220, -1));
        bg.add(regdate_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 220, -1));

        accstatus_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accstatus_fldActionPerformed(evt);
            }
        });
        bg.add(accstatus_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 220, -1));

        cam_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cam_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/211634_camera_icon.png"))); // NOI18N
        bg.add(cam_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 110, 50));

        save_btn.setText("Save Changes");
        save_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_btnMouseClicked(evt);
            }
        });
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        bg.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 110, -1));

        deactivate_btn.setText("Deactivate Account");
        deactivate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivate_btnActionPerformed(evt);
            }
        });
        bg.add(deactivate_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        viewact_btn.setText("View Activity");
        viewact_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewact_btnActionPerformed(evt);
            }
        });
        bg.add(viewact_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upload_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upload_btnActionPerformed

    private void name_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fldActionPerformed

    private void accstatus_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accstatus_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accstatus_fldActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
    
    }//GEN-LAST:event_save_btnActionPerformed

    private void deactivate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivate_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deactivate_btnActionPerformed

    private void viewact_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewact_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewact_btnActionPerformed

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedback_btnActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilebtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        
    }//GEN-LAST:event_homebtnActionPerformed

    private void save_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_btnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_save_btnMouseClicked

    private void discoverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoverbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discoverbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accstatus_fld;
    private javax.swing.JLabel accstatus_lbl;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bookingsbtn;
    private javax.swing.JLabel cam_lbl;
    private javax.swing.JButton deactivate_btn;
    private javax.swing.JButton discoverbtn;
    private javax.swing.JTextField email_fld;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JButton myeventsbtn;
    private javax.swing.JTextField name_fld;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField phone_fld;
    private javax.swing.JLabel phone_lbl;
    private javax.swing.JLabel pic_lbl;
    private javax.swing.JButton profilebtn;
    private javax.swing.JTextField regdate_fld;
    private javax.swing.JLabel regdate_lbl;
    private javax.swing.JButton save_btn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel taskbar;
    private javax.swing.JButton upload_btn;
    private javax.swing.JButton viewact_btn;
    // End of variables declaration//GEN-END:variables
}
