/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.eventCardController;
import Model.Booker;
import Model.EventData;
import dao.BookingDao;
import java.util.ArrayList;
import javax.swing.Box;

/**
 *
 * @author thismac
 */
public class bookersList extends javax.swing.JPanel {
    private int eID;
    private final BookingDao dao = new BookingDao();
    /**
     * Creates new form bookersList
     */
    public bookersList(int eID) {
        this.eID = eID;
        initComponents();
        bookersList.setLayout(new javax.swing.BoxLayout(bookersList, javax.swing.BoxLayout.Y_AXIS));
        bookersList.setPreferredSize(null);
        getSetBookers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookersList = new javax.swing.JPanel();

        javax.swing.GroupLayout bookersListLayout = new javax.swing.GroupLayout(bookersList);
        bookersList.setLayout(bookersListLayout);
        bookersListLayout.setHorizontalGroup(
            bookersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        bookersListLayout.setVerticalGroup(
            bookersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(bookersList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bookersList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void getSetBookers(){
        ArrayList<Booker> bookers = dao.getBookersByEventId(eID);
        bookersList.removeAll();
        
        for (Booker booker : bookers) {
            UserCard user = new UserCard(booker);
            user.ban_btn.setVisible(false);
            bookersList.add(user);
            bookersList.add(Box.createVerticalStrut(10));
        }

        bookersList.revalidate();
        bookersList.repaint();
        
    }
}
