/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.LocalTime;

import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author hp
 */
public class CreateEvent extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public CreateEvent() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        feedback_btn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        bookingsbtn = new javax.swing.JButton();
        myeventsbtn = new javax.swing.JButton();
        discoverbtn = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        plus_btn = new javax.swing.JButton();
        taskbar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        img_fld = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        eventtype = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        limit = new javax.swing.JLabel();
        deadline = new javax.swing.JLabel();
        event_img = new javax.swing.JLabel();
        cam_lbl = new javax.swing.JLabel();
        create_btn = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_fld = new javax.swing.JTextArea();
        deadline_fld = new javax.swing.JTextField();
        title_fld = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        eventcategory_box = new javax.swing.JComboBox<>();
        price_fld = new javax.swing.JTextField();
        location_fld = new javax.swing.JTextField();
        end_fld = new javax.swing.JTextField();
        event_status = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        limit_fld = new javax.swing.JTextField();
        date_fld = new javax.swing.JTextField();
        tickettype = new javax.swing.JLabel();
        ticketype_box = new javax.swing.JComboBox<>();
        eventtype_box = new javax.swing.JComboBox<>();
        start = new javax.swing.JLabel();
        start_fld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(208, 202, 232));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedback_btn.setBackground(new java.awt.Color(208, 202, 232));
        feedback_btn.setText("Feedback");
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });
        sidebar.add(feedback_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, 50));

        homebtn.setBackground(new java.awt.Color(208, 202, 232));
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        sidebar.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 50));

        bookingsbtn.setBackground(new java.awt.Color(208, 202, 232));
        bookingsbtn.setText("Bookings");
        sidebar.add(bookingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 50));

        myeventsbtn.setBackground(new java.awt.Color(208, 202, 232));
        myeventsbtn.setText("My Events");
        myeventsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myeventsbtnActionPerformed(evt);
            }
        });
        sidebar.add(myeventsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 50));

        discoverbtn.setBackground(new java.awt.Color(208, 202, 232));
        discoverbtn.setText("Discover");
        discoverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverbtnActionPerformed(evt);
            }
        });
        sidebar.add(discoverbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 50));

        profilebtn.setBackground(new java.awt.Color(208, 202, 232));
        profilebtn.setText("Profile");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        sidebar.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 50));

        logout_btn.setBackground(new java.awt.Color(208, 202, 232));
        logout_btn.setText("Log Out");
        sidebar.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 220, 40));

        plus_btn.setBackground(new java.awt.Color(208, 202, 232));
        plus_btn.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        plus_btn.setText("+");
        plus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_btnActionPerformed(evt);
            }
        });
        sidebar.add(plus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 223, 60, 60));

        bg.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 260, 630));

        taskbar.setBackground(new java.awt.Color(229, 179, 208));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Event Scheduling");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N

        javax.swing.GroupLayout taskbarLayout = new javax.swing.GroupLayout(taskbar);
        taskbar.setLayout(taskbarLayout);
        taskbarLayout.setHorizontalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        taskbarLayout.setVerticalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 710, 40));

        img_fld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.add(img_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 120, 110));

        title.setText("Event Title");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        description.setText("Description");
        bg.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        category.setText("Category");
        bg.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        eventtype.setText("Type");
        bg.add(eventtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        end.setText("End Time");
        bg.add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, 10));

        location.setText("Location");
        bg.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        limit.setText("Participant Limit");
        bg.add(limit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        deadline.setText("RSVP Deadline");
        bg.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        event_img.setText("Image Banner");
        bg.add(event_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        cam_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cam_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/211634_camera_icon.png"))); // NOI18N
        bg.add(cam_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 40, 40));

        create_btn.setBackground(new java.awt.Color(180, 175, 204));
        create_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        create_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_btn.setText("Create");
        bg.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 573, 540, 40));

        price.setText("Price");
        bg.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        description_fld.setColumns(20);
        description_fld.setRows(5);
        jScrollPane1.setViewportView(description_fld);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 510, 60));
        bg.add(deadline_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 80, -1));
        bg.add(title_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 500, -1));

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Draft", "Published" }));
        bg.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, -1, -1));

        eventcategory_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arts & Culture", "Food & Drink", "Sports & Outdoors", "Education & Learning", "Business & Networking", "Family & Kids", "Community & Charity", "Lifestyle & Hobbies", "Seasonal & Holiday", "Online/Virtual Events" }));
        eventcategory_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventcategory_boxActionPerformed(evt);
            }
        });
        bg.add(eventcategory_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));
        bg.add(price_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 90, -1));
        bg.add(location_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 220, -1));
        bg.add(end_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 80, -1));

        event_status.setText("Event Status");
        bg.add(event_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        date.setText("Date");
        bg.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        limit_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limit_fldActionPerformed(evt);
            }
        });
        bg.add(limit_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, -1));
        bg.add(date_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 90, -1));

        tickettype.setText("Ticket Type");
        bg.add(tickettype, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        ticketype_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Free" }));
        ticketype_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketype_boxActionPerformed(evt);
            }
        });
        bg.add(ticketype_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        eventtype_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Private", "Public" }));
        eventtype_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventtype_boxActionPerformed(evt);
            }
        });
        bg.add(eventtype_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        start.setText("Start Time");
        bg.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));
        bg.add(start_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_feedback_btnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_feedback_btnActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_profilebtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_homebtnActionPerformed

    }// GEN-LAST:event_homebtnActionPerformed

    private void discoverbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_discoverbtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_discoverbtnActionPerformed

    private void status_fldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_status_fldActionPerformed

    }// GEN-LAST:event_status_fldActionPerformed

    private void eventcategory_boxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_eventcategory_boxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_eventcategory_boxActionPerformed

    private void ticketype_boxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ticketype_boxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ticketype_boxActionPerformed

    private void myeventsbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_myeventsbtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_myeventsbtnActionPerformed

    private void plus_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plus_btnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_plus_btnActionPerformed

    private void limit_fldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limit_fldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_limit_fldActionPerformed

    private void eventtype_boxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_eventtype_boxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_eventtype_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bookingsbtn;
    private javax.swing.JLabel cam_lbl;
    private javax.swing.JLabel category;
    private javax.swing.JButton create_btn;
    private javax.swing.JLabel date;
    private javax.swing.JTextField date_fld;
    private javax.swing.JLabel deadline;
    private javax.swing.JTextField deadline_fld;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea description_fld;
    private javax.swing.JButton discoverbtn;
    private javax.swing.JLabel end;
    private javax.swing.JTextField end_fld;
    private javax.swing.JLabel event_img;
    private javax.swing.JLabel event_status;
    private javax.swing.JComboBox<String> eventcategory_box;
    private javax.swing.JLabel eventtype;
    private javax.swing.JComboBox<String> eventtype_box;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel img_fld;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel limit;
    private javax.swing.JTextField limit_fld;
    private javax.swing.JLabel location;
    private javax.swing.JTextField location_fld;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton myeventsbtn;
    private javax.swing.JButton plus_btn;
    private javax.swing.JLabel price;
    private javax.swing.JTextField price_fld;
    private javax.swing.JButton profilebtn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel start;
    private javax.swing.JTextField start_fld;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JPanel taskbar;
    private javax.swing.JLabel tickettype;
    private javax.swing.JComboBox<String> ticketype_box;
    private javax.swing.JLabel title;
    private javax.swing.JTextField title_fld;
    // End of variables declaration//GEN-END:variables

    public String getEventTitle() {
        return title_fld.getText();
    }

    public String getEventLocation() {
        return location_fld.getText();
    }

    public String getEventDescription() {
        return description_fld.getText();
    }

    public String getEventCategory() {
        return (String) eventcategory_box.getSelectedItem();
    }

    public String getEventType() {
        return (String) eventtype_box.getSelectedItem();
    }

    public String getTicketType() {
        return (String) ticketype_box.getSelectedItem();
    }

    public LocalDate getEventDate() {
        // Assuming start_fld contains event date as text yyyy-mm-dd
        return LocalDate.parse(date_fld.getText());
    }

    public LocalTime getStartTime() {
        return LocalTime.parse(start_fld.getText());
    }

    public LocalTime getEndTime() {
        return LocalTime.parse(end_fld.getText());
    }

    public LocalDate getRsvpDeadline() {
        return LocalDate.parse(deadline_fld.getText());
    }

    public double getEventPrice() {
        return Double.parseDouble(price_fld.getText());
    }

    public int getTicketsAvailable() {
        return Integer.parseInt(limit_fld.getText());
    }
    
    public String getEventStatus() {
        return statusComboBox.getSelectedItem().toString();
    }

    public void addEventStatusListener(ActionListener listener) {
        statusComboBox.addActionListener(listener);
    }


    public void clearFields() {
        title_fld.setText("");
        location_fld.setText("");
        description_fld.setText("");
        eventcategory_box.setSelectedIndex(0);
        eventtype_box.setSelectedIndex(0);
        ticketype_box.setSelectedIndex(0);

        if (date_fld.getText().equals("yyyy-mm-dd") || date_fld.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid event date in yyyy-mm-dd format.");
            return;
        }

        price_fld.setText("");
        limit_fld.setText("");
    }

    // btns
    public void addAddEventListener(ActionListener listener) {
        create_btn.addActionListener(listener);
    }

    public void addLogoutListener(ActionListener listener) {
        logout_btn.addActionListener(listener);
    }

    public void addProfileListener(ActionListener listener) {
        profilebtn.addActionListener(listener);
    }

    public void addCreateEventListener(ActionListener listener) {
        plus_btn.addActionListener(listener);
    }

    public void addBookingListener(ActionListener listener) {
        bookingsbtn.addActionListener(listener);
    }

    public void addHomeListener(ActionListener listener) {
        homebtn.addActionListener(listener);
    }

    public void addDiscoverListener(ActionListener listener) {
        discoverbtn.addActionListener(listener);
    }

    public void addMyEventsListener(ActionListener listener) {
        myeventsbtn.addActionListener(listener);
    }

}
