/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import Model.*;
import dao.UserDao;
import util.SessionUtil;

/**
 *
 * @author hp
 */
public class UserCard extends javax.swing.JPanel {
 private Booker booker;
 private UserData user;
 private final UserDao dao = new UserDao();
    /**
     * Creates new form UserCard
     */
    public UserCard(Booker booker) {
        this.booker = booker;
        this.user = null;
        initComponents(); 
        setBookers();
    }

    public UserCard(UserData user) {
        this.booker = null;
        this.user = user;
        initComponents(); 
        setUsers();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JLabel();
        ban_btn = new javax.swing.JButton();
        namelbl = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tickets = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile.png"))); // NOI18N

        ban_btn.setForeground(new java.awt.Color(255, 51, 51));
        ban_btn.setText("Ban");
        ban_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ban_btnMouseClicked(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        namelbl.setText("name");

        number.setText("number");

        email.setText("Email");

        tickets.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tickets.setText("20 Tickets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(ban_btn))
                    .addComponent(tickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namelbl)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email))
                            .addComponent(ban_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(tickets))
                    .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ban_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ban_btnMouseClicked
       if(ban_btn.getText().equals("Ban")){
           dao.updateUserStatus(user.getId(), "banned");
           ban_btn.setText("Un-Ban");
       }else{
           dao.updateUserStatus(user.getId(), "active");
           ban_btn.setText("Ban");
       
       }
    }//GEN-LAST:event_ban_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ban_btn;
    public javax.swing.JLabel dp;
    public javax.swing.JLabel email;
    public javax.swing.JLabel namelbl;
    public javax.swing.JLabel number;
    public javax.swing.JLabel tickets;
    // End of variables declaration//GEN-END:variables

    public void setBookers() {
        namelbl.setText("Name: " + booker.getUsername());
        number.setText("Number: "+ booker.getPhone());
        email.setText("Email : "+ booker.getEmail());
        tickets.setText((booker.getTicketCount()>0)? Integer.toString(booker.getTicketCount())+" tickets" : "");
        
        String path = booker.getImagePath();
        if (path != null && !path.isEmpty()) {
            try {
                ImageIcon originalIcon = new ImageIcon(path);
                Image originalImage = originalIcon.getImage();

                // Resize image to 140x140
                Image scaledImage = originalImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);

                // Set the scaled image as icon
                dp.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {
                e.printStackTrace(); 
            }
        }
        
        ban_btn.setVisible(false);
    }
    
    public void setUsers() {
        namelbl.setText("Name: " + user.getUsername());
        number.setText("Number: "+ user.getPhone());
        email.setText("Email : "+ user.getEmail());
        tickets.setVisible(false);
        
        String path = user.getImagePath();
        if (path != null && !path.isEmpty()) {
            try {
                ImageIcon originalIcon = new ImageIcon(path);
                Image originalImage = originalIcon.getImage();

                // Resize image to 140x140
                Image scaledImage = originalImage.getScaledInstance(100, 100, Image.SCALE_SMOOTH);

                // Set the scaled image as icon
                dp.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {
                e.printStackTrace(); 
            }
        }
        
        if(user.getStatus().equals("banned")){
            ban_btn.setText("Un-Ban");
        }else {
            ban_btn.setText("Ban");
        }
    }
    
    

    public JButton getActionButton() {
        return ban_btn;
    }
}
